### ISSUE TITLE
리스트 추가 요청입니다

### ISSUE THREAD

**Issue by ombe1229** [nomadcoders/nomadcoders-github-list#113]
**Slack Nickname:** ombe

**Comment by DalYoon** [comment]
신청해주셔서 감사합니다
근데 슬랙에 ombe 라는 닉네임으로 검색되는분이 없는데
슬랙에 들어와 계신가요? :)

**Comment by ombe1229** [comment]
다시 한번만 확인 부탁드립니다!

**Comment by ShigatsuEl** [comment]
안녕하세요 :)
슬랙에서 노마드 깃헙을 알게되어 댓글을 남기게 되었습니다.
Slack Name -> 이민찬
입니다!

**Comment by flynnpark** [comment]
@ShigatsuEl 안녕하세요. 이슈나 풀리퀘를 새로 등록해주시면 됩니다.
