### ISSUE TITLE
리스트 추가 요청입니다

### ISSUE THREAD

**Issue by chemtae** [nomadcoders/nomadcoders-github-list#132]
NomadCoders Profile: https://nomadcoders.co/users/taeroo612
Slack Nickname: Chemtae Shin

**Comment by flynnpark** [comment]
앗 저거 `_` 사이에 있는 거 지우시고 본인 것만 써 넣어 주시면 되는데 ㅠ.ㅠ

**Comment by chemtae** [comment]
헉...? 네 알겠습니다! 다시볼게요! 영문몰라서 좀 몰랐습니다...!

2021년 1월 4일 (월) 오후 9:50, Flynn (Inho Park) <notifications@github.com>님이 작성:

**Comment by flynnpark** [comment]
한 번 수정만 슬쩍 부탁드립니다!

**Comment by chemtae** [comment]
제가 맞게한건지 확인부탁드립니다(꾸벅)

2021년 1월 4일 (월) 오후 9:52, Flynn (Inho Park) <notifications@github.com>님이 작성:

**Comment by flynnpark** [comment]
NomadCoders Profile: https://nomadcoders.co/users/taeroo612
Slack Nickname: Chemtae Shin

요렇게입니다 ㅎㅎ

**Comment by flynnpark** [comment]
템플릿을 좀 더 이해하기 쉽게 수정해야겠네요

**Comment by chemtae** [comment]
헉 알려주신대로 다시 고칠게요ㅜㅠ!!
제가 이런쪽으로 엄청 문외한이라 많이 헤매는것같습니다!! 죄송해용ㅜㅠ

2021년 1월 4일 (월) 오후 10:01, Flynn (Inho Park) <notifications@github.com>님이 작성:

**Comment by chemtae** [comment]
쨘...!!

**Comment by flynnpark** [comment]
아닙니다 ㅎㅎ 저도 좀 더 잘 쓸 수 있도록 템플릿 업데이트 했습니다... 휴

**Comment by chemtae** [comment]
절받으세요 플린님(꾸벅) 감사합니다

**Comment by chemtae** [comment]
Thanks!

2021년 1월 4일 (월) 오후 10:16, Flynn (Inho Park) <notifications@github.com>님이 작성:
